### ISSUE TITLE
VU+ Zero - "noforce.update" needs to be "force.update"

### ISSUE THREAD

**Issue by Pr0metheus2** [Pedro-Newbie/BackupSuite#17]
Hi,
when creating backup on VU+ Zero, plugin creates file **noforce.update**, but actually, this file has to be renamed to **force.update** to get upgrade process done. Since VU+ Zero has no display at all, update process must be done automatically.

So I recommend to create file **force.update** instead of **noforce.update**.

**Comment by Pedro-Newbie** [comment]
It is done intentional, if the user forgets to remove the USB from the STB and he restart e.g. 10 days later after an update the flash starts automatic restoring the STB to 10 days ago and maybe deleting timers etc.

So it is done on purpose

 

Van: Andrej Tobola [mailto:notifications@github.com] 
Verzonden: maandag 6 maart 2017 21:18
Aan: Pedro-Newbie/BackupSuite
CC: Subscribed
Onderwerp: [Pedro-Newbie/BackupSuite] VU+ Zero "noforce.update" needs to be "force.update" (#17)

 

Hi,
when creating backup on VU+ Zero, plugin creates file noforce.update, but actually, this file has to be renamed to force.update to get upgrade process done. Since VU+ Zero has no display at all, update process must be done automatically.

So I recommend to create file force.update instead of noforce.update.

**Comment by Pr0metheus2** [comment]
Understand. But in this case, can we put some extra information on the screen for VU Zero users that "In order to update receiver, noforce.update file in vu/zero folder needs to be renamed to force.update" ?
Would that be much work to implement this?

**Comment by Pedro-Newbie** [comment]
Done!
